### ISSUE TITLE
bug about data

### ISSUE THREAD

**Issue by lxx01110** [Zehong-Wang/GFT#1]
Hello, thank you so much for sharing such an excellent codebase and project! I have learned a lot from your work, and it has been incredibly helpful for my research/study.

However, I encountered an issue when running the code, and I would greatly appreciate your assistance. The specific error message is as follows:
<img width="643" alt="image" src="https://github.com/user-attachments/assets/5816fa63-824b-48ee-b13b-3d20998cf9c4">
I followed the environment setup instructions in the README.md file and ran the pretrain.py script according to the steps provided in the README.md. However, the above error occurred. Based on the error message, it seems there is an issue with the JSON file corresponding to WikiCS. I manually added ] and } symbols to the JSON file to make it complete. However, another bug then appeared, as shown below：
<img width="917" alt="image" src="https://github.com/user-attachments/assets/dc58ea0e-828d-4399-ab8e-b614f6dea91e">

**Comment by Zehong-Wang** [comment]
@lxx01110 Thank you for letting us know. Could you please explain where the first bug occurred in our code and what JSON file you modified? This would significantly help us check the code.

**Comment by lxx01110** [comment]
> @lxx01110 Thank you for letting us know. Could you please explain where the first bug occurred in our code and what JSON file you modified? This would significantly help us check the code.

The bug I mentioned above has been resolved, probably due to not having the full data downloaded. I used conda env create -f environment.yml to download the environment according to the instructions in the readme.md file, but I still didn't install the datasets and pyg-lib libraries, and I have installed them manually. However, the following problems arise:
<img width="711" alt="image" src="https://github.com/user-attachments/assets/81d10934-ebe2-4d8b-802e-eb70dc98b0bd">

**Comment by Zehong-Wang** [comment]
@lxx01110 Thank you for your response. We have re-run the process and found that the pipeline is working correctly. Could you please try reinstalling the environment? If you encounter any issues, don’t hesitate to let us know. Based on the snapshot provided, we suspect the issue might be related to the pyg version. Our project uses pyg 2.3, so if your version is higher, you may want to consider downgrading it.

**Comment by Zehong-Wang** [comment]
@lxx01110 Hello, kindly let us know if you’ve resolved the issue. If not, we’ll be glad to assist you further.

**Comment by lxx01110** [comment]
> @lxx01110 Hello, kindly let us know if you’ve resolved the issue. If not, we’ll be glad to assist you further.

Thank you so much for your willingness to take the time to solve my problem. I've reconfigured my environment and am currently running pretrain.py, and if there is no problem in the end, I'll let you know right away. Thank you again for your generous help.

**Comment by lxx01110** [comment]
> @lxx01110 Hello, kindly let us know if you’ve resolved the issue. If not, we’ll be glad to assist you further.

Hello, zehong, I have reproduced the results, thank you very much for your careful help. The above error may be because I have multiple virtual environments actived at the same time, and when I run your code, the base virtual environment is called, so the version  is incorrect. Thank you very much for the novel idea as well as the code, it will be a huge help to my research, thank you very much!
